### ISSUE TITLE
PhantomJS not found

### ISSUE THREAD

**Issue by rtsio** [zpratt/karma-mocha-chai#1]
FYI, your tutorial and repo do not work, as launching a test will result in

```
INFO [launcher]: Starting browser PhantomJS
ERROR [launcher]: No binary for PhantomJS browser on your platform.
  Please, set "PHANTOMJS_BIN" env variable.
```

You should probably go over how to install PhantomJS and set the path.

**Comment by wmyers** [comment]
Same as previous post `"karma-phantomjs-launcher": "~0.1.4"` was in package.json but I was getting the `No binary for PhantomJS browser` error. I ran `npm install karma-phantomjs-launcher` which appeared to install for the first time, then I was able to run tests fine.

**Comment by goldcaddy77** [comment]
Running `npm install karma-phantomjs-launcher` will fix this temporarily, but if you want to fix it permanently, you can upgrade your version of node and re-install your npm packages:

OSX
```
npm cache clean -f
brew upgrade nodejs
rm -rf node_modules
npm install -g YOUR_GLOBAL_DEPENDENCIES
npm install
```

**Comment by wmyers** [comment]
What finally fixed it for me was setting a PHANTOM_JS environment variable and pointing it directly to phantomjs.exe on my local system. [This post](https://github.com/karma-runner/karma-phantomjs-launcher/issues/31#issuecomment-47202373), and the next few, clarify it.

**Comment by rjauquet** [comment]
Might be obvious, but this also happens when you cancel the npm install of phantom after the `npm_modules/phantomjs` folder is created. In that case, removing **phantomjs** (and **karma-phantomjs-launcher** for me) and rerunning `npm install` fixes everything.
