### ISSUE TITLE
What is the expected failing test?

### ISSUE THREAD

**Issue by martinhbramwell** [zpratt/karma-mocha-chai#2]
Your README says :  "After running `npm test` you should see a failing test"

This is not the error I should see, is it?

```
 > karma-mocha-chai@0.0.2 test /home/yourself/BDD/kmc
 > grunt

 sh: 1: grunt: not found
 npm ERR! Test failed.  See above for more details.
```

Is there some special way of installing grunt?  I am using : `npm install grunt`  without success.

(I'm completely new to JS testing, test-runners, Node, etc. and really appreciate your examples.  It is amazing how hard it is to find a clear route map for this jungle.)

**Comment by zpratt** [comment]
I've updated the README to include instructions for installing global npm project dependencies.

**Comment by martinhbramwell** [comment]
Thanks.  In my research and experimentation I discovered and switched to using, Meteor, which eliminates much of the guesswork for this stuff.
